const BUTTON_BACKGROUND_GRADIENT = ['#002584', '#0087DB', '#0098EA'];
const BUTTON_NAME_COMMON = '#FFFFFF';
const INPUT_BACKGROUND = '#FFFFFF';
const INPUT_ERROR = '#FF0000';
const INPUT_PLACEHOLDER = '#0F0F108C';
const SCREEN_BACKGROUND = '#F5F5F5';
const TEXT_COMMON = '#010101';

const COLORS = {
  BUTTON_BACKGROUND_GRADIENT,
  BUTTON_NAME_COMMON,
  INPUT_BACKGROUND,
  INPUT_ERROR,
  INPUT_PLACEHOLDER,
  SCREEN_BACKGROUND,
  TEXT_COMMON,
};

export default COLORS;
